const axios = require('axios');

// Extended restaurant ingredients with prices
const ingredients = [
    // Basic Proteins
    { name: "Chicken Breast", price: 12.99 },
    { name: "Chicken Thighs", price: 10.99 },
    { name: "Ground Beef", price: 18.99 },
    { name: "Beef Steak", price: 24.99 },
    { name: "Pork Chops", price: 16.99 },
    { name: "Bacon", price: 8.99 },
    { name: "Turkey", price: 14.99 },
    { name: "Lamb", price: 22.99 },
    { name: "Duck", price: 28.99 },
    { name: "Salmon", price: 24.99 },
    { name: "Tuna", price: 20.99 },
    { name: "Cod", price: 18.99 },
    { name: "Shrimp", price: 26.99 },
    { name: "Lobster", price: 45.99 },
    { name: "Crab", price: 32.99 },
    { name: "Mussels", price: 15.99 },
    { name: "Clams", price: 12.99 },
    { name: "Eggs", price: 5.99 },
    { name: "Quail Eggs", price: 8.99 },
    
    // Vegetables
    { name: "Tomatoes", price: 2.50 },
    { name: "Cherry Tomatoes", price: 3.99 },
    { name: "Roma Tomatoes", price: 2.99 },
    { name: "Lettuce", price: 2.99 },
    { name: "Romaine Lettuce", price: 3.99 },
    { name: "Spinach", price: 4.99 },
    { name: "Kale", price: 4.99 },
    { name: "Arugula", price: 5.99 },
    { name: "Cucumber", price: 2.99 },
    { name: "Onion", price: 2.49 },
    { name: "Red Onion", price: 2.99 },
    { name: "Shallots", price: 4.99 },
    { name: "Garlic", price: 2.99 },
    { name: "Ginger", price: 3.49 },
    { name: "Carrots", price: 2.99 },
    { name: "Broccoli", price: 3.99 },
    { name: "Cauliflower", price: 3.99 },
    { name: "Bell Peppers", price: 4.99 },
    { name: "Jalapeños", price: 3.99 },
    { name: "Mushrooms", price: 5.99 },
    { name: "Portobello Mushrooms", price: 7.99 },
    { name: "Shiitake Mushrooms", price: 8.99 },
    { name: "Zucchini", price: 3.99 },
    { name: "Eggplant", price: 4.99 },
    { name: "Asparagus", price: 6.99 },
    { name: "Green Beans", price: 3.99 },
    { name: "Peas", price: 3.99 },
    { name: "Corn", price: 2.99 },
    { name: "Sweet Potato", price: 3.99 },
    { name: "Potatoes", price: 4.99 },
    { name: "Red Potatoes", price: 5.99 },
    { name: "Yukon Gold Potatoes", price: 5.99 },
    { name: "Avocado", price: 3.99 },
    { name: "Lime", price: 1.49 },
    { name: "Lemon", price: 1.99 },
    { name: "Orange", price: 2.49 },
    { name: "Grapefruit", price: 2.99 },
    { name: "Apples", price: 3.99 },
    { name: "Pears", price: 4.99 },
    { name: "Grapes", price: 5.99 },
    { name: "Strawberries", price: 6.99 },
    { name: "Blueberries", price: 7.99 },
    { name: "Raspberries", price: 8.99 },
    { name: "Blackberries", price: 7.99 },
    { name: "Mango", price: 3.99 },
    { name: "Pineapple", price: 4.99 },
    { name: "Banana", price: 2.99 },
    { name: "Kiwi", price: 3.99 },
    { name: "Pomegranate", price: 5.99 },
    { name: "Coconut", price: 4.99 },
    
    // Dairy & Eggs
    { name: "Milk", price: 4.99 },
    { name: "Heavy Cream", price: 6.99 },
    { name: "Half & Half", price: 5.99 },
    { name: "Butter", price: 6.99 },
    { name: "Cheese", price: 7.99 },
    { name: "Cheddar Cheese", price: 8.99 },
    { name: "Mozzarella", price: 8.99 },
    { name: "Parmesan Cheese", price: 9.99 },
    { name: "Feta Cheese", price: 8.99 },
    { name: "Blue Cheese", price: 10.99 },
    { name: "Gouda", price: 9.99 },
    { name: "Brie", price: 11.99 },
    { name: "Cream Cheese", price: 5.99 },
    { name: "Ricotta", price: 6.99 },
    { name: "Yogurt", price: 4.99 },
    { name: "Greek Yogurt", price: 5.99 },
    { name: "Sour Cream", price: 3.99 },
    { name: "Whipped Cream", price: 4.99 },
    
    // Grains & Breads
    { name: "Rice", price: 6.99 },
    { name: "Brown Rice", price: 7.99 },
    { name: "Basmati Rice", price: 8.99 },
    { name: "Jasmine Rice", price: 8.99 },
    { name: "Quinoa", price: 8.99 },
    { name: "Pasta", price: 5.99 },
    { name: "Spaghetti", price: 5.99 },
    { name: "Penne", price: 5.99 },
    { name: "Fettuccine", price: 5.99 },
    { name: "Linguine", price: 5.99 },
    { name: "Ravioli", price: 7.99 },
    { name: "Tortellini", price: 7.99 },
    { name: "Noodles", price: 4.99 },
    { name: "Ramen Noodles", price: 3.99 },
    { name: "Udon Noodles", price: 5.99 },
    { name: "Soba Noodles", price: 6.99 },
    { name: "Bread", price: 3.99 },
    { name: "Sourdough Bread", price: 5.99 },
    { name: "Whole Wheat Bread", price: 4.99 },
    { name: "Baguette", price: 4.99 },
    { name: "Burger Buns", price: 3.99 },
    { name: "Hot Dog Buns", price: 3.99 },
    { name: "Tortillas", price: 4.99 },
    { name: "Pizza Dough", price: 4.50 },
    { name: "Flour", price: 4.99 },
    { name: "All-Purpose Flour", price: 4.99 },
    { name: "Bread Flour", price: 5.99 },
    { name: "Cake Flour", price: 5.99 },
    { name: "Whole Wheat Flour", price: 5.99 },
    { name: "Cornmeal", price: 3.99 },
    { name: "Oats", price: 4.99 },
    { name: "Cereal", price: 5.99 },
    
    // Nuts & Seeds
    { name: "Almonds", price: 12.99 },
    { name: "Walnuts", price: 11.99 },
    { name: "Pecans", price: 13.99 },
    { name: "Cashews", price: 14.99 },
    { name: "Pistachios", price: 15.99 },
    { name: "Pine Nuts", price: 18.99 },
    { name: "Sunflower Seeds", price: 6.99 },
    { name: "Pumpkin Seeds", price: 7.99 },
    { name: "Chia Seeds", price: 8.99 },
    { name: "Flax Seeds", price: 7.99 },
    { name: "Sesame Seeds", price: 5.99 },
    
    // Legumes
    { name: "Chickpeas", price: 3.99 },
    { name: "Black Beans", price: 3.99 },
    { name: "Kidney Beans", price: 3.99 },
    { name: "Pinto Beans", price: 3.99 },
    { name: "Lentils", price: 4.99 },
    { name: "Split Peas", price: 3.99 },
    { name: "Edamame", price: 5.99 },
    
    // Oils & Fats
    { name: "Olive Oil", price: 12.99 },
    { name: "Extra Virgin Olive Oil", price: 15.99 },
    { name: "Vegetable Oil", price: 8.99 },
    { name: "Coconut Oil", price: 10.99 },
    { name: "Sesame Oil", price: 9.99 },
    { name: "Truffle Oil", price: 25.99 },
    { name: "Ghee", price: 11.99 },
    { name: "Lard", price: 7.99 },
    
    // Sauces & Condiments
    { name: "Soy Sauce", price: 3.99 },
    { name: "Fish Sauce", price: 4.99 },
    { name: "Oyster Sauce", price: 4.99 },
    { name: "Hoisin Sauce", price: 4.99 },
    { name: "Teriyaki Sauce", price: 4.99 },
    { name: "Worcestershire Sauce", price: 3.99 },
    { name: "Hot Sauce", price: 3.99 },
    { name: "Sriracha", price: 4.99 },
    { name: "Ketchup", price: 2.99 },
    { name: "Mustard", price: 2.99 },
    { name: "Mayonnaise", price: 3.99 },
    { name: "Ranch Dressing", price: 3.99 },
    { name: "Caesar Dressing", price: 5.99 },
    { name: "Balsamic Vinegar", price: 6.99 },
    { name: "Apple Cider Vinegar", price: 4.99 },
    { name: "White Vinegar", price: 2.99 },
    { name: "Red Wine Vinegar", price: 5.99 },
    { name: "BBQ Sauce", price: 4.99 },
    { name: "Marinara Sauce", price: 4.99 },
    { name: "Alfredo Sauce", price: 5.99 },
    { name: "Pesto", price: 6.99 },
    { name: "Hummus", price: 5.99 },
    { name: "Tahini", price: 6.99 },
    { name: "Peanut Butter", price: 5.99 },
    { name: "Almond Butter", price: 8.99 },
    { name: "Jelly", price: 3.99 },
    { name: "Jam", price: 3.99 },
    { name: "Honey", price: 7.99 },
    { name: "Maple Syrup", price: 8.99 },
    { name: "Agave Nectar", price: 6.99 },
    
    // Spices & Herbs
    { name: "Salt", price: 1.99 },
    { name: "Black Pepper", price: 6.99 },
    { name: "White Pepper", price: 7.99 },
    { name: "Garlic Powder", price: 4.99 },
    { name: "Onion Powder", price: 4.99 },
    { name: "Paprika", price: 4.99 },
    { name: "Cayenne Pepper", price: 5.99 },
    { name: "Chili Powder", price: 4.99 },
    { name: "Cumin", price: 4.99 },
    { name: "Coriander", price: 4.99 },
    { name: "Turmeric", price: 4.99 },
    { name: "Curry Powder", price: 5.99 },
    { name: "Ginger Powder", price: 4.99 },
    { name: "Cinnamon", price: 4.99 },
    { name: "Nutmeg", price: 5.99 },
    { name: "Allspice", price: 5.99 },
    { name: "Cloves", price: 5.99 },
    { name: "Cardamom", price: 6.99 },
    { name: "Saffron", price: 25.99 },
    { name: "Vanilla Extract", price: 8.99 },
    { name: "Almond Extract", price: 7.99 },
    { name: "Basil", price: 3.99 },
    { name: "Oregano", price: 3.99 },
    { name: "Thyme", price: 4.99 },
    { name: "Rosemary", price: 4.99 },
    { name: "Sage", price: 4.99 },
    { name: "Parsley", price: 3.99 },
    { name: "Cilantro", price: 3.99 },
    { name: "Mint", price: 3.99 },
    { name: "Dill", price: 3.99 },
    { name: "Bay Leaves", price: 4.99 },
    { name: "Herbs", price: 4.99 },
    
    // Baking Ingredients
    { name: "Sugar", price: 3.99 },
    { name: "Brown Sugar", price: 4.99 },
    { name: "Powdered Sugar", price: 4.99 },
    { name: "Baking Soda", price: 2.99 },
    { name: "Baking Powder", price: 3.99 },
    { name: "Yeast", price: 4.99 },
    { name: "Cornstarch", price: 3.99 },
    { name: "Gelatin", price: 4.99 },
    { name: "Chocolate", price: 8.99 },
    { name: "Dark Chocolate", price: 9.99 },
    { name: "White Chocolate", price: 8.99 },
    { name: "Chocolate Chips", price: 7.99 },
    { name: "Cocoa Powder", price: 6.99 },
    { name: "Vanilla Bean", price: 12.99 },
    { name: "Food Coloring", price: 3.99 },
    { name: "Sprinkles", price: 3.99 },
    
    // Beverages & Alcohol
    { name: "Coffee", price: 12.99 },
    { name: "Tea", price: 8.99 },
    { name: "Green Tea", price: 9.99 },
    { name: "Black Tea", price: 8.99 },
    { name: "Herbal Tea", price: 9.99 },
    { name: "Red Wine", price: 18.99 },
    { name: "White Wine", price: 15.99 },
    { name: "Beer", price: 12.99 },
    { name: "Vodka", price: 25.99 },
    { name: "Gin", price: 28.99 },
    { name: "Rum", price: 22.99 },
    { name: "Whiskey", price: 35.99 },
    { name: "Tequila", price: 30.99 },
    { name: "Sherry", price: 18.99 },
    { name: "Brandy", price: 32.99 },
    { name: "Liqueur", price: 20.99 },
    
    // Snacks & Processed Foods
    { name: "Popcorn", price: 3.99 },
    { name: "Potato Chips", price: 4.99 },
    { name: "Tortilla Chips", price: 4.99 },
    { name: "Crackers", price: 3.99 },
    { name: "Pretzels", price: 3.99 },
    { name: "Nuts Mix", price: 12.99 },
    { name: "Trail Mix", price: 8.99 },
    { name: "Granola", price: 6.99 },
    { name: "Protein Bars", price: 8.99 },
    { name: "Energy Bars", price: 7.99 },
    { name: "Cereal Bars", price: 5.99 },
    { name: "Cookies", price: 4.99 },
    { name: "Brownies", price: 5.99 },
    { name: "Muffins", price: 4.99 },
    { name: "Donuts", price: 3.99 },
    { name: "Cupcakes", price: 4.99 },
    { name: "Ice Cream", price: 6.99 },
    { name: "Sorbet", price: 5.99 },
    { name: "Frozen Yogurt", price: 5.99 },
    { name: "Popsicles", price: 3.99 },
    { name: "Candy", price: 4.99 },
    { name: "Chocolate Bars", price: 3.99 },
    { name: "Gum", price: 2.99 },
    { name: "Mints", price: 2.99 },
    
    // Special Ingredients
    { name: "Truffle", price: 150.99 },
    { name: "Caviar", price: 200.99 },
    { name: "Foie Gras", price: 85.99 },
    { name: "Wagyu Beef", price: 120.99 },
    { name: "Kobe Beef", price: 180.99 },
    { name: "Wild Mushrooms", price: 15.99 },
    { name: "Morel Mushrooms", price: 25.99 },
    { name: "Chanterelle Mushrooms", price: 22.99 },
    { name: "Porcini Mushrooms", price: 18.99 },
    { name: "Black Truffle Oil", price: 35.99 },
    { name: "White Truffle Oil", price: 45.99 },
    { name: "Saffron Threads", price: 45.99 },
    { name: "Vanilla Beans", price: 18.99 },
    { name: "Tahini Paste", price: 8.99 },
    { name: "Miso Paste", price: 6.99 },
    { name: "Wasabi", price: 5.99 },
    { name: "Nori Sheets", price: 7.99 },
    { name: "Rice Vinegar", price: 4.99 },
    { name: "Mirin", price: 5.99 },
    { name: "Sake", price: 15.99 },
    { name: "Shaoxing Wine", price: 8.99 },
    { name: "Fish Stock", price: 6.99 },
    { name: "Chicken Stock", price: 5.99 },
    { name: "Beef Stock", price: 6.99 },
    { name: "Vegetable Stock", price: 4.99 },
    { name: "Bouillon Cubes", price: 3.99 },
    { name: "Gelatin Sheets", price: 8.99 },
    { name: "Agar Agar", price: 7.99 },
    { name: "Xanthan Gum", price: 9.99 },
    { name: "Guar Gum", price: 8.99 },
    { name: "Pectin", price: 6.99 },
    { name: "Citric Acid", price: 4.99 },
    { name: "Malic Acid", price: 5.99 },
    { name: "Tartaric Acid", price: 5.99 },
    { name: "Lecithin", price: 7.99 },
    { name: "Whey Protein", price: 15.99 },
    { name: "Casein Protein", price: 18.99 },
    { name: "Soy Protein", price: 12.99 },
    { name: "Pea Protein", price: 14.99 },
    { name: "Hemp Protein", price: 16.99 },
    { name: "Spirulina", price: 20.99 },
    { name: "Chlorella", price: 22.99 },
    { name: "Moringa", price: 18.99 },
    { name: "Matcha Powder", price: 25.99 },
    { name: "Maca Powder", price: 20.99 },
    { name: "Acai Powder", price: 30.99 },
    { name: "Goji Berries", price: 25.99 },
    { name: "Golden Berries", price: 18.99 },
    { name: "Mulberries", price: 22.99 },
    { name: "Dragon Fruit", price: 8.99 },
    { name: "Passion Fruit", price: 6.99 },
    { name: "Guava", price: 5.99 },
    { name: "Lychee", price: 7.99 },
    { name: "Rambutan", price: 8.99 },
    { name: "Durian", price: 15.99 },
    { name: "Jackfruit", price: 12.99 },
    { name: "Breadfruit", price: 10.99 },
    { name: "Plantains", price: 4.99 },
    { name: "Yuca", price: 3.99 },
    { name: "Taro", price: 4.99 },
    { name: "Jicama", price: 3.99 },
    { name: "Daikon", price: 3.99 },
    { name: "Bok Choy", price: 4.99 },
    { name: "Napa Cabbage", price: 3.99 },
    { name: "Chinese Cabbage", price: 3.99 },
    { name: "Watercress", price: 5.99 },
    { name: "Endive", price: 4.99 },
    { name: "Radicchio", price: 5.99 },
    { name: "Frisée", price: 4.99 },
    { name: "Mizuna", price: 5.99 },
    { name: "Tatsoi", price: 5.99 },
    { name: "Komatsuna", price: 5.99 },
    { name: "Chard", price: 4.99 },
    { name: "Collard Greens", price: 3.99 },
    { name: "Mustard Greens", price: 3.99 },
    { name: "Turnip Greens", price: 3.99 },
    { name: "Beet Greens", price: 4.99 },
    { name: "Dandelion Greens", price: 4.99 },
    { name: "Purslane", price: 5.99 },
    { name: "Sorrel", price: 6.99 },
    { name: "Nettles", price: 7.99 },
    { name: "Lamb's Quarters", price: 5.99 },
    { name: "Amaranth Greens", price: 5.99 },
    { name: "Malabar Spinach", price: 6.99 },
    { name: "New Zealand Spinach", price: 6.99 },
    { name: "Orach", price: 7.99 },
    { name: "Good King Henry", price: 8.99 },
    { name: "Fat Hen", price: 5.99 },
    { name: "Goosefoot", price: 5.99 },
    { name: "Pigweed", price: 4.99 },
    { name: "Quinoa Greens", price: 6.99 },
    { name: "Beetroot", price: 3.99 },
    { name: "Turnips", price: 3.99 },
    { name: "Rutabaga", price: 3.99 },
    { name: "Parsnips", price: 4.99 },
    { name: "Celeriac", price: 4.99 },
    { name: "Kohlrabi", price: 4.99 },
    { name: "Radishes", price: 2.99 },
    { name: "Watermelon Radish", price: 4.99 },
    { name: "Daikon Radish", price: 3.99 },
    { name: "Black Radish", price: 4.99 },
    { name: "Horseradish", price: 5.99 },
    { name: "Wasabi Root", price: 25.99 },
    { name: "Ginger Root", price: 3.49 },
    { name: "Turmeric Root", price: 4.99 },
    { name: "Galangal", price: 8.99 },
    { name: "Lemongrass", price: 4.99 },
    { name: "Kaffir Lime Leaves", price: 6.99 },
    { name: "Curry Leaves", price: 5.99 },
    { name: "Bay Leaves", price: 4.99 },
    { name: "Lime Leaves", price: 5.99 },
    { name: "Orange Leaves", price: 4.99 },
    { name: "Lemon Leaves", price: 4.99 },
    { name: "Grape Leaves", price: 5.99 },
    { name: "Cabbage Leaves", price: 2.99 },
    { name: "Lettuce Leaves", price: 2.99 },
    { name: "Spinach Leaves", price: 4.99 },
    { name: "Kale Leaves", price: 4.99 },
    { name: "Chard Leaves", price: 4.99 },
    { name: "Collard Leaves", price: 3.99 },
    { name: "Mustard Leaves", price: 3.99 },
    { name: "Turnip Leaves", price: 3.99 },
    { name: "Beet Leaves", price: 4.99 },
    { name: "Dandelion Leaves", price: 4.99 },
    { name: "Purslane Leaves", price: 5.99 },
    { name: "Sorrel Leaves", price: 6.99 },
    { name: "Nettle Leaves", price: 7.99 },
    { name: "Lamb's Quarter Leaves", price: 5.99 },
    { name: "Amaranth Leaves", price: 5.99 },
    { name: "Malabar Spinach Leaves", price: 6.99 },
    { name: "New Zealand Spinach Leaves", price: 6.99 },
    { name: "Orach Leaves", price: 7.99 },
    { name: "Good King Henry Leaves", price: 8.99 },
    { name: "Fat Hen Leaves", price: 5.99 },
    { name: "Goosefoot Leaves", price: 5.99 },
    { name: "Pigweed Leaves", price: 4.99 },
    { name: "Quinoa Leaves", price: 6.99 }
];

async function populateIngredients() {
    console.log('Starting to populate extended ingredients...');
    
    for (let i = 0; i < ingredients.length; i++) {
        const ingredient = ingredients[i];
        
        try {
            const response = await axios.post('http://localhost:3000/ingredients', {
                name: ingredient.name,
                price: ingredient.price
            });
            
            console.log(`✅ Added: ${ingredient.name} - $${ingredient.price} (ID: ${response.data._id})`);
            
            // Small delay to avoid overwhelming the server
            await new Promise(resolve => setTimeout(resolve, 50));
            
        } catch (error) {
            console.error(`❌ Failed to add ${ingredient.name}:`, error.response?.data || error.message);
        }
    }
    
    console.log('Finished populating extended ingredients!');
}

// Run the population script
populateIngredients().catch(console.error); 